# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: wan's blog
email: wan.lm@foxmail.com
name: wan.lm
description: >- # this means to ignore newlines until "baseurl:"
  writing&thinking.
keywords: [humanities]
baseurl: '' # the subpath of your site, e.g. /`blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'wanliming.github.io' # the domain name for your site, e.g. example.com
language: zh-cn,en
# Supported languages list:
# en: English
# de: Deutsche (German)
# es: Español (Spanish)
# fr: Français (French)
# ja: 日本語 (Japanese)
# pt: Português (Portuguese)
# zh-cn: 简体中文 (Simplified Chinese)
# zh-tw: 繁體中文 (Traditional Chinese)

analytics: # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: true # enable comments
disqus: vgtn # disqus account

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 2500
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Category settings
jekyll-archives:
  enabled: 
  - catagories
  layout: archive

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
